version: 2.1

executors:
  macos-on-cloud:
    macos:
      xcode: 12.5.1
  macos122-on-runner:
    machine: true
    resource_class: mayoct/runner-m122
  macos123-on-runner:
    machine: true
    resource_class: mayoct/runner-m123

jobs: # a basic unit of work in a run
  display_system_info:
    parameters:
      executor_name:
        type: string
    executor:
      name: <<parameters.executor_name >>
    steps:
      - run:
          name: Display system information
          command: system_profiler SPHardwareDataType
      
  test: # your job name
    parameters:
      executor_name:
        type: string
    executor:
      name: <<parameters.executor_name >>
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme circleci-demo-macos

  build: 
    parameters:
      executor_name:
        type: string
    executor:
      name: <<parameters.executor_name >>
    steps: 
      - checkout
      - run:
          # build our application
          name: Build Application
          command: xcodebuild
      - run:
          # compress Xcode's build output so that it can be stored as an artifact
          name: Compress app for storage
          command: zip -r app.zip build/Release/circleci-demo-macos.app
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: app.zip
          destination: app
          
workflows:
  version: 2
  test_build:
    jobs:
      - display_system_info:
          name: 'Display Info on macOS on Cloud'
          executor_name: macos-on-cloud
      - test:
          name: 'Test on macOS on Cloud'
          executor_name: macos-on-cloud
          requires:
            - display_system_info
      - build:
          name: 'Build on macOS on Cloud'
          executor_name: macos-on-cloud
          requires:
            - test

      - display_system_info:
          name: 'Display Info on macOS on macOS 12.2 on Runner'
          executor_name: macos122-on-runner
      - test:
          name: 'Test Info on macOS on macOS 12.2 on Runner'
          executor_name: macos122-on-runner
          requires:
            - display_system_info
      - build:
          name: 'Build Info on macOS on macOS 12.2 on Runner'
          executor_name: macos122-on-runner
          requires:
            - test

      - display_system_info:
          name: 'Display Info on macOS on macOS 12.3 beta on Runner'
          executor_name: macos123-on-runner
      - test:
          name: 'Test Info on macOS on macOS 12.3 beta on Runner'
          executor_name: macos123-on-runner
          requires:
            - display_system_info
      - build:
          name: 'Build Info on macOS on macOS 12.3 beta on Runner'
          executor_name: macos123-on-runner
          requires:
            - test